#!/bin/sh
set -e

FLATPAK_APPS="
    com.discordapp.Discord
    org.kicad.KiCad
    com.slack.Slack
"

case "$1" in
    configure)
        flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

        for app in $FLATPAK_APPS; do
            flatpak install --noninteractive flathub "$app"
        done
        ;;
    configure|upgrade)
        flatpak update --noninteractive
        ;;
esac